topology_path: config/topology_sample.yaml
simulation:
  time_steps: 100
  time_step_duration_ms: 100

topology:
  type: sample
  nodes: 5
  edges: 6

routing:
  algorithm: qcea
  weights: {}

traffic:
  - class: test
    src: 1
    dst: 4
    rate_kbps: 64

weights:
    wl: 0.5
    wb: 0.1
    wp: 0.1
    we: 0.4
    wc: 0.05
  
